[default]
SESSION_TYPE = 'filesystem'
SECRET_KEY = "@jinja {{env['SECRET_KEY'] or 'segredo'}}"
SQLALCHEMY_DATABASE_URI = "@jinja {{env['DATABASE_URI']}}"
SQLALCHEMY_TRACK_MODIFICATIONS = 'False'
APP_NAME = "@jinja {{env['APP_NAME'] or 'Palpites'}}"
RBAC_USE_WHITE = 'True'
VERSION = '0.1.0'
EXTENSIONS = [
    'palpites.ext.database',
    'palpites.ext.auth',
    'palpites.ext.cli',
    'palpites.blueprints.views',
    'palpites.blueprints.grupo',
    'palpites.blueprints.auth'
]
API_FUTEBOL = "@jinja {{env['API_FUTEBOL']}}"
