[default]
SESSION_TYPE = 'filesystem'
SECRET_KEY = "@jinja {{env['SECRET_KEY'] or 'segredo'}}"
SQLALCHEMY_DATABASE_URI = "sqlite:///banco.db"
SQLALCHEMY_TRACK_MODIFICATIONS = 'False'
APP_NAME = "@jinja {{env['APP_NAME'] or 'Palpites'}}"
VERSION = '0.1.0'
EXTENSIONS = [
    'palpites.ext.database',
    'palpites.ext.cli',
    'palpites.ext.authorization',
    'palpites.blueprints.views'
]