[default]
SESSION_TYPE = 'filesystem'
SECRET_KEY = "@jinja {{env['SECRET_KEY']}}"
SQLALCHEMY_DATABASE_URI = "sqlite:///banco.db"
SQLALCHEMY_TRACK_MODIFICATIONS = 'False'
APP_NAME = "@jinja {{env['APP_NAME']}}"
EXTENSIONS = [
    'palpites.ext.database',
    'palpites.ext.cli',
    'palpites.blueprints.views'
]